import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import style from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.container}>
        <h1>Home page</h1>
        <Link href="/auth/login">Sign In</Link>
        <Link href="/auth/signup">Sign up</Link>
      </div>
    </>
  );
}

